version: '2'

services:
  api:
    tty: true
    stdin_open: true
    build: .
    image: lukeulrich/mist3-api
    volumes:
      # The source code is placed in a subdirectory of $HOME to avoid mapping trivial configuration
      # files (e.g. .bash_history) created in the docker environment from mapping to out source code
      # directory
      - .:/home/mist3/api
    ports:
      - 5858:5858 # Node debugging port
    container_name: api
    # Not yet running a server therefore open bash shell to keep container running (when using
    # $ docker-compose up -d)
    command: bash -c "npm run setup && /bin/bash"
